---

test_name: Test Tag Microservices

stages:
        - name: Add an article with a new tag
          request:
                url: http://localhost:4000/article/tag
                method: POST
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: List all articles with a new tag
          request:
                url: http://localhost:4000/article/
                method: POST
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: Add another tag to the article
          request:
                url: http://localhost:4000/article/
                method: POST
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: Delete one of the tags from the article
          request:
                url: http://localhost:4000/article/
                json:
                        articleId: 1
                method: DELETE
          response:
                  status_code: 404

---

test_name: Test Tag Microservices

stages:
        - name: Add a tag to an article that doesn't exist
          request:
                url: http://localhost:4000/article/tag/22/
                json:
                        username: enrrique
                        password: test
                method: POST
                headers:
                        content-type: application/json
          response:
                  status_code: 404