---

test_name: Test Comments Microservices

includes:
        - !include includes.yaml

stages:
        - name: Try to add a comment to an article that doesn't exist
          request:
                url: "http://localhost:{commentP:d}/article/"
                method: POST
          response:
                  status_code: 404

---

test_name: Test Comments Microservices

includes:
        - !include includes.yaml

stages:
        - name: Post an anonymous comment on an article
          request:
                url: "http://localhost:{commentP:d}/article/"
                method: POST
          response:
                  status_code: 404

---

test_name: Test Comments Microservices

includes:
        - !include includes.yaml

stages:
        - name: Post an authenticated comment on an article
          request:
                url: "http://localhost:{commentP:d}/article/"
                method: POST
          response:
                  status_code: 404

---

test_name: Test Comments Microservices

includes:
        - !include includes.yaml

stages:
        - name: Check that the comments on the article were returnd in order
          request:
                url: "http://localhost:{commentP:d}/article/"
                method: POST
          response:
                  status_code: 404