---

test_name: Test Articles Microservices

stages:
        - name: Try to post an article without authenticating
          request:
                url: http://localhost:3000/article/new/
                method: POST
          response:
                  status_code: 404

---

test_name: Test Articles Microservices

stages:
        - name: Try to post an article using the wrong password
          request:
                url: http://localhost:3000/article/new/
                method: POST
          response:
                  status_code: 404

---

test_name: Test Articles Microservices

stages:
        - name: Post an article successfully
          request:
                url: http://localhost:3000/article/new/
                method: POST
          response:
                  status_code: 404

---

test_name: Test Articles Microservices

stages:
        - name: Retriece the newly posted article
          request:
                url: http://localhost:3000/article/22
                method: POST
          response:
                  status_code: 405

---

test_name: Test Articles Microservices

stages:
        - name: Check that the newly posted article is the most recent
          request:
                url: http://localhost:3000/article/1
                method: POST
          response:
                  status_code: 405
